version: "3.4"

networks:
  DRYBOX-dev:
    driver: bridge

services:
  DRYBOX:
    image: DRYBOX:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=DRYBOX-db;username=DRYBOX-db;password=DRYBOX-db"
    networks:
      - DRYBOX-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "DRYBOX-db"
      POSTGRES_PASSWORD: "DRYBOX-db"
      POSTGRES_DB: "DRYBOX-db"
    networks:
      - DRYBOX-dev
volumes:
  db_volume:
